// Public because the Messenger API takes it as a parameter type (it used to be passed as a
// boxed object, which allocated on every Register/Send/Unregister call).
public enum MessageContext
{
    LoaderToBrain,
    UiToBrain,
    UiToTrace,
    UiToTaskPerformanceMessage,
    UiToVideo,
    UiToEvents,
    UiToTFEvents,
    UiToLayouts,
    EventsToTraceMessage,
    EventsToTaskPerformanceMessage,
    EventsModificationMessage,
    BrainWardenToElectrodePointerMessage,
    ReactionTimePointerMessage,
    TraceDisplayerPointerMessage,
    TraceDisplayerNormalize,
    BrainWardenToTraceMessage,
    ModulesToVideoMessage,
    VideoToModulesMessage,
    FileMenuMessage,
    EditMenuMessage,
    LoadSubjectMessage,
    LoaderMessage,
    ShowWindowMessage,
    ForceUpdateTraceMessage,
    ShortcutMessage,
    ForceToggleToolbar,
    ProcessCalculationMessage,
    TimeFrequencyResultMessage,
    EventsToEventsMessage,
    MontageMessage
}
